/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "NextDistribution": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "PrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "cloudflaremulti-MyBucketAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "cloudflaremulti-MyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "cloudflaremulti-RevalidationSeeder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "server-default": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "server-imageOptimizer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "server-regional": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "server-regionaleu-west-3": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "server-regionalus-west-1": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}